import React from 'react'
import { Link } from 'react-router-dom'
import LegalPage from '../components/legal/LegalPage'
import { PAGES, LEGAL_ENTITY, LAST_UPDATED } from '../seo/seoConfig'

export default function TermsOfService() {
  return (
    <LegalPage
      eyebrow="LEGAL"
      title="Terms of Service"
      intro="These terms form the agreement between you and NucleusAi Automation Private Limited when you use Puja Havan to book pandits, order samagri or use our astrology tools."
      lastUpdated={LAST_UPDATED}
      seo={PAGES['terms-of-service']}
    >
      <h2>1. Agreement</h2>
      <p>
        {LEGAL_ENTITY.domain} is owned and operated by {LEGAL_ENTITY.name}. By accessing the
        site, creating a booking or using any of our tools, you agree to these Terms, our{' '}
        <Link to="/privacy-policy">Privacy Policy</Link>,{' '}
        <Link to="/refund-policy">Refund &amp; Cancellation Policy</Link> and{' '}
        <Link to="/cookie-policy">Cookie Policy</Link>. If you do not agree, please do not use
        the platform.
      </p>
      <p>You must be at least 18 years old and able to enter a binding contract under Indian law.</p>

      <h2>2. What Puja Havan is</h2>
      <p>
        We are a <strong>technology platform that connects you with independent pandits and
        purohits</strong>. We verify pandits before listing them, coordinate the booking and
        handle payment, but the ritual itself is performed by the pandit as an independent
        practitioner and not as our employee.
      </p>
      <p>
        Descriptions of ceremonies, their benefits and their significance are provided for
        information based on traditional Vedic texts and belief. They are religious and cultural
        practices — they are <strong>not</strong> medical, legal, financial or psychological
        advice, and no particular outcome, result or fulfilment of a wish is promised or
        guaranteed.
      </p>

      <h2>3. Bookings</h2>
      <ul>
        <li>A booking is confirmed only after we accept it and payment (or the agreed advance) is received.</li>
        <li>Prices shown are per-package starting prices; the final amount depends on the package, samagri, travel and any customisation, and is shown before you pay.</li>
        <li>Muhurat and timing suggestions follow standard Panchang calculations; you are responsible for confirming a date that suits you.</li>
        <li>We may reassign a pandit of equivalent qualification if the assigned pandit becomes unavailable. If no substitute is acceptable to you, you receive a full refund.</li>
        <li>You must provide safe, lawful access to the venue and the facilities the ceremony reasonably requires (space for havan kund, ventilation, water and electricity where applicable).</li>
      </ul>

      <h2>4. Payments</h2>
      <ul>
        <li>Payments are processed by Razorpay. We do not store your card, UPI or banking credentials.</li>
        <li>All fees are in Indian Rupees (INR) and inclusive of applicable taxes unless stated otherwise.</li>
        <li>Any dakshina you offer the pandit beyond the package price is voluntary and directly to them.</li>
        <li>We may change prices at any time, but never for a booking already confirmed.</li>
      </ul>

      <h2>5. Cancellation and refunds</h2>
      <p>
        Cancellations, reschedules and refunds are governed by our{' '}
        <Link to="/refund-policy">Refund &amp; Cancellation Policy</Link>, which forms part of
        these Terms.
      </p>

      <h2>6. Astrology tools</h2>
      <p>
        Our Kundali, Panchang and Numerology tools are generated by software from the birth or
        date details you provide, using standard astronomical and traditional calculation
        methods. Results depend entirely on the accuracy of your input. These tools are offered
        for personal, informational and cultural interest only, free of charge, with no warranty
        of accuracy, and must not be relied upon for medical, legal, financial or other
        significant decisions.
      </p>

      <h2>7. Your responsibilities</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Provide false, misleading or someone else&rsquo;s information.</li>
        <li>Harass, abuse, discriminate against or endanger a pandit or our staff.</li>
        <li>Use the platform for anything unlawful, or for any ritual intended to cause harm to another person.</li>
        <li>Attempt to bypass the platform to avoid fees after being introduced to a pandit through us.</li>
        <li>Copy, scrape, reverse-engineer or resell any part of the platform or its content.</li>
        <li>Upload malicious code or attempt to disrupt, overload or gain unauthorised access to our systems.</li>
      </ul>
      <p>We may suspend or terminate access for any breach of these Terms.</p>

      <h2>8. Intellectual property</h2>
      <p>
        All content on the platform — including the Puja Havan name and logo, page design, text,
        poster artwork, photographs and software — is owned by {LEGAL_ENTITY.name} or its
        licensors and is protected by Indian and international intellectual property law. You may
        view and share it for personal, non-commercial use; any other use requires our written
        permission.
      </p>

      <h2>9. Third-party services</h2>
      <p>
        We rely on third parties such as payment gateways, mapping and geocoding providers, cloud
        hosting and messaging services. Their availability and conduct are outside our control,
        and their own terms apply to their services.
      </p>

      <h2>10. Disclaimers and limitation of liability</h2>
      <p>
        The platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.
        We do not warrant uninterrupted or error-free operation.
      </p>
      <p>
        To the maximum extent permitted by law, our total liability for any claim arising out of
        or relating to a booking is limited to the amount you actually paid us for that booking.
        We are not liable for indirect, incidental, special or consequential losses, or for loss
        of profit, opportunity or reputation.
      </p>
      <p>
        Nothing in these Terms excludes liability that cannot be excluded under Indian law,
        including liability for fraud or for death or personal injury caused by our negligence.
      </p>

      <h2>11. Indemnity</h2>
      <p>
        You agree to indemnify and hold harmless {LEGAL_ENTITY.name}, its directors, employees
        and listed pandits against claims, damages and reasonable legal costs arising from your
        breach of these Terms, your misuse of the platform, or your violation of any law or
        third-party right.
      </p>

      <h2>12. Force majeure</h2>
      <p>
        We are not liable for failure or delay caused by events beyond our reasonable control,
        including natural disasters, epidemics, government restrictions, civil unrest, strikes,
        power or internet failure. Where a ceremony cannot proceed for such a reason, we will
        offer a reschedule or a refund of amounts not already irrecoverably spent.
      </p>

      <h2>13. Grievance redressal</h2>
      <p>
        Please write to <a href={`mailto:${LEGAL_ENTITY.email}`}>{LEGAL_ENTITY.email}</a> or call{' '}
        <a href={`tel:${LEGAL_ENTITY.phoneHref}`}>{LEGAL_ENTITY.phoneDisplay}</a>. We acknowledge
        complaints within 48 hours and aim to resolve them within 30 days. Our Grievance Officer
        is named in the <Link to="/privacy-policy">Privacy Policy</Link>.
      </p>

      <h2>14. Governing law and jurisdiction</h2>
      <p>
        These Terms are governed by the laws of India. Subject to the grievance process above,
        the courts at {LEGAL_ENTITY.jurisdiction} shall have exclusive jurisdiction over any
        dispute.
      </p>

      <h2>15. Changes to these Terms</h2>
      <p>
        We may amend these Terms at any time. The version published on this page at the time of
        your booking governs that booking. Continued use of the platform after an update means
        you accept the revised Terms.
      </p>
    </LegalPage>
  )
}
